### ISSUE TITLE
Hibernate error when first starting the application

### ISSUE THREAD

**Issue by sdumitriu** [phenotips/remote-matching#12]
Build and start a fresh PhenomeCentral, open it in the browser. You'll get the following exception in the logs, but everything works fine otherwise, and the error doesn't happen again for the following restart.

```
Caused by: org.hibernate.HibernateException: Failed updating schema while executing query [alter table PUBLIC.HibernatePatient add constraint FK32B78E73FBF628EE foreign key (requestentity_id) references PUBLIC.remote_matching_requests]
        at com.xpn.xwiki.store.XWikiHibernateBaseStore.updateSchema(XWikiHibernateBaseStore.java:596) [xwiki-platform-oldcore-5.4.6.jar:na]
        at com.xpn.xwiki.store.XWikiHibernateBaseStore.updateSchema(XWikiHibernateBaseStore.java:341) [xwiki-platform-oldcore-5.4.6.jar:na]
        at com.xpn.xwiki.store.migration.hibernate.HibernateDataMigrationManager.hibernateShemaUpdate(HibernateDataMigrationManager.java:196) [xwiki-platform-oldcore-5.4.6.jar:na]
        at com.xpn.xwiki.store.migration.hibernate.HibernateDataMigrationManager.updateSchema(HibernateDataMigrationManager.java:178) [xwiki-platform-oldcore-5.4.6.jar:na]
        ... 63 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: a FOREIGN KEY constraint already exists on the set of columns: FK32B78E73FBF628EE in statement [alter table PUBLIC.HibernatePatient add constraint FK32B78E73FBF628EE foreign key (requestentity_id) references PUBLIC.remote_matching_requests]
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.hsqldb.jdbc.JDBCStatement.executeUpdate(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228) ~[commons-dbcp-1.3.jar:1.3]
        at org.apache.commons.dbcp.DelegatingStatement.executeUpdate(DelegatingStatement.java:228) ~[commons-dbcp-1.3.jar:1.3]
        at com.xpn.xwiki.store.XWikiHibernateBaseStore.updateSchema(XWikiHibernateBaseStore.java:592) [xwiki-platform-oldcore-5.4.6.jar:na]
        ... 66 common frames omitted
Caused by: org.hsqldb.HsqlException: a FOREIGN KEY constraint already exists on the set of columns: FK32B78E73FBF628EE
        at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.hsqldb.TableWorks.checkCreateForeignKey(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.hsqldb.TableWorks.addForeignKey(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.hsqldb.StatementSchema.getResult(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.hsqldb.StatementSchema.execute(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.hsqldb.Session.executeDirectStatement(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
        at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]

**Comment by pijushcse** [comment]
what was solution to fix this problem?
